name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
        name: Deploy to server
        runs-on: ubuntu-latest

        steps:
        - name: Install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Connect and deploy
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd pidor.dev && git pull && exit"
        - name: Cleanup
          run: rm -rf ~/.ssh

